
services:
  aostp-dashboard:
    image: ${DOCKER_IMAGE_NAME:-teincsolutions/aostp-dashboard-test}:${DOCKER_TAG:-latest}
    container_name: aostp-dashboard-test
    restart: always
    env_file:
      - .env.test
    ports:
      - "8081:8080"
    networks:
      - aostp-internal-net

networks:
  aostp-internal-net:
    external: true
