// src/types/package.ts

export interface PackagePhotoInput {
  url: string;
  key: string;
}

export interface PackagePhoto {
  id: string;
  url: string;
  key: string;
  uploadedAt: string;
}

export interface Customer {
  id: string;
  customerCode: string;
  firstName: string;
  lastName: string;
  email?: string;
  phoneNumber?: string;
  alternatePhone?: string;
  address?: string;
  city?: string;
  country?: string;
  idType?: string;
  idNumber?: string;
  preferredChannel?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PackageIntakePayload {
  customerId: string;
  trackingCode?: string; // Generated by backend, optional for create
  description?: string;
  weight: number;
  cbm: number;
  quantity: number;
  value: number;
  shippingMode: "SEA" | "AIR";
  airShippingType?: string;
  warehouseLocation: string;
  notes?: string;
  photos?: PackagePhotoInput[];
}

export interface PackageIntake {
  id: string;
  trackingCode: string;
  customerId: string;
  customer: Customer;
  description?: string;
  weight: number;
  cbm: number;
  quantity: number;
  value: number;
  shippingMode: "SEA" | "AIR";
  airShippingType?: string | null;
  status: string;
  receivedDate: string;
  warehouseLocation: string;
  daysInWarehouse: number;
  notes?: string;
  packingListId?: string | null;
  invoiceId?: string | null;
  paymentStatus: string;
  createdById: string;
  updatedById?: string | null;
  photos: PackagePhoto[];
  packingList?: any | null;
  invoice?: any | null;
  createdAt: string;
  updatedAt: string;
  onViewReceipt?: (id: string) => void;
}

export interface Receipt {
  id: string;
  packageId: string;
  url: string;
  createdAt: string;
}

export enum ShipmentType {
  AIR = "AIR",
  SEA = "SEA",
}

export enum PackageStatus {
  RECEIVED = "RECEIVED",
  PACKED = "PACKED",
  IN_TRANSIT = "IN_TRANSIT",
  DELIVERED = "DELIVERED",
}

export interface Package {
  id: string;
  trackingNumber: string;
  customer: {
    firstName: string;
    lastName: string;
    [key: string]: any;
  };
  description?: string;
  weight: number;
  cbm: number;
  shipmentType: ShipmentType;
  status: PackageStatus;
  createdAt: string;
  // Add other fields as needed
}
