// src/types/package.ts

export interface PackagePhotoInput {
  url: string;
  key: string;
}

export interface PackagePhoto {
  id: string;
  url: string;
  key: string;
  uploadedAt: string;
}

export interface Customer {
  id: string;
  customerCode: string;
  firstName: string;
  lastName: string;
  email?: string;
  phoneNumber?: string;
  alternatePhone?: string;
  address?: string;
  city?: string;
  country?: string;
  idType?: string;
  idNumber?: string;
  preferredChannel?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PackageIntakePayload {
  customerId: string;
  trackingCode?: string; // Generated by backend, optional for create
  description?: string;
  weight?: number; // Optional - added during package management before packing lists
  cbm?: number; // Optional - added during package management before packing lists
  quantity: number;
  value: number;
  shippingMode: "SEA" | "AIR";
  airShippingType?: string;
  warehouseLocation: string;
  notes?: string;
  photos?: PackagePhotoInput[];
}

export interface PackageIntake {
  id: string;
  trackingCode: string;
  customerId: string;
  customer: Customer;
  description?: string;
  weight: number;
  cbm: number;
  quantity: number;
  value: number;
  shippingMode: "SEA" | "AIR";
  airShippingType?: string | null;
  status: string;
  receivedDate: string;
  warehouseLocation: string;
  daysInWarehouse: number;
  notes?: string;
  packingListId?: string | null;
  invoiceId?: string | null;
  paymentStatus: string;
  createdById: string;
  updatedById?: string | null;
  photos: PackagePhoto[];
  packingList?: any | null;
  invoice?: any | null;
  createdAt: string;
  updatedAt: string;
  onViewReceipt?: (id: string) => void;
}

export interface Receipt {
  id: string;
  packageId: string;
  url: string;
  createdAt: string;
}

// Package Status enum for package-dependent logic and UI
export enum PackageStatus {
  RECEIVED = "RECEIVED",
  CONSOLIDATED = "CONSOLIDATED",
  RELEASED = "RELEASED",
}

// Package status for packages table
export enum PackageStatusPackages {
  IN_WAREHOUSE = "IN_WAREHOUSE",
  ASSIGNED = "ASSIGNED",
  SHIPPED = "SHIPPED",
  ARRIVED = "ARRIVED",
  RELEASED = "RELEASED",
}

export enum ShipmentType {
  AIR = "AIR",
  SEA = "SEA",
}

export enum AirType {
  EXPRESS = "EXPRESS",
  STANDARD = "STANDARD",
}

// Package Items (Physical units from intake)
export interface PackageItem {
  item_id: string;
  intake_tracking_code: string;
  customer_code: string;
  description?: string;
  quantity: number;
  weight?: number;
  cbm?: number;
  photos: PackagePhoto[];
  status: PackageStatus;
  package_id?: string; // FK to packages when consolidated
  warehouse_id: string;
  created_at: string;
  updated_at: string;
}

// Packages (Trackable units - consolidated or single)
export interface Package {
  package_id: string;
  tracking_code: string;
  customer_code: string;
  mode: ShipmentType;
  air_type?: AirType;
  destination_city_id: string;
  warehouse_id: string;
  is_consolidated: boolean;
  quantity: number; // Always 1 for consolidated packages
  weight?: number; // Auto-computed from items
  cbm?: number; // Auto-computed from items
  status: PackageStatusPackages;
  notes?: string;
  created_at: string;
  updated_at: string;
  // Relations
  items?: PackageItem[];
  photos?: PackagePhoto[];
}
